# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.10 on 2017-02-12 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 1.10.5 on 2017-02-12 19:13
from __future__ import unicode_literals

from django.db import migrations, models
>>>>>>> 3b3f517aec6e98ef1f398d1daede2741a6958cf0


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name=b'date published')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Question'),
        ),
=======
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_text', models.CharField(max_length=200)),
                ('data_money', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
>>>>>>> 3b3f517aec6e98ef1f398d1daede2741a6958cf0
    ]
